### ISSUE TITLE
maybe-app-service not starting in docker

### ISSUE THREAD

**Issue by pronoym99** [maybe-finance/maybe#1124]
I have been unable to get the `app` container to start among the two containers present in the docker app (`postgres` being the other). I have a custom `docker-compose.yml` file which I have pasted below. I don't intend to populate my root drive with Docker data so I have created dedicated directories in `F:/DockerData/maybe/` and mounted them appropriately.

```
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    command: ["sh", "-c", "echo 'App service started!'"] # Placeholder command
    volumes:
      - type: bind
        source: F:/DockerData/maybe/app-storage
        target: /rails/storage
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      SELF_HOSTING_ENABLED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - type: bind
        source: F:/DockerData/maybe/postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app-storage:
    driver: local
    driver_opts:
      type: none
      device: F:/DockerData/maybe/app-storage
      o: bind
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: F:/DockerData/maybe/postgres-data
      o: bind
```

As a result, the app is not available at `http://localhost:3000`. I have tried restarting it directly via Docker desktop, the `postgres` container works perfectly while the `app` container hangs in the restarting state.
