### ISSUE TITLE
Bug: ERROR:  column "type" of relation "imports" contains null values

### ISSUE THREAD

**Issue by athiosh** [maybe-finance/maybe#1224]
Pulled the latest image and received the following message in the Logs. I am getting 502 error when accessing the site.

App Log
```
== 20240925112218 AddImportTypes: migrating ===================================

-- change_table(:imports)

To use multipart middleware with Faraday v2.0+, install `faraday-multipart` gem; note: this is used by the ManageGHES client for uploading licenses

bin/rails aborted!

StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::NotNullViolation: ERROR:  column "type" of relation "imports" contains null values

/rails/db/migrate/20240925112218_add_import_types.rb:4:in `block in change'

/rails/db/migrate/20240925112218_add_import_types.rb:3:in `change'

Caused by:

ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  column "type" of relation "imports" contains null values (ActiveRecord::NotNullViolation)

/rails/db/migrate/20240925112218_add_import_types.rb:4:in `block in change'

/rails/db/migrate/20240925112218_add_import_types.rb:3:in `change'

Caused by:

PG::NotNullViolation: ERROR:  column "type" of relation "imports" contains null values (PG::NotNullViolation)

/rails/db/migrate/20240925112218_add_import_types.rb:4:in `block in change'

/rails/db/migrate/20240925112218_add_import_types.rb:3:in `change'

Tasks: TOP => db:prepare

(See full trace by running task with --trace)

I, [2024-10-01T19:44:54.701919 #7]  INFO -- : Migrating to AddImportTypes (20240925112218)
```

Server Log
```
2024-10-01 19:42:22.158 UTC [82] ERROR:  column "type" of relation "imports" contains null values

2024-10-01 19:42:22.158 UTC [82] STATEMENT:  ALTER TABLE "imports" ADD "type" character varying NOT NULL
```

docker-compose
```yaml
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - /appdata/maybe/storage:/rails/storage
    ports:
      - 5743:3000
    restart: unless-stopped
    environment:
      SELF_HOSTING_ENABLED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    env_file:
      - stack.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /appdata/maybe/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
```
