### ISSUE TITLE
Account charts always several days behind

### ISSUE THREAD

**Issue by JustinGeorgi** [maybe-finance/maybe#1403]
**Describe the bug**
All charts of account values or net work cover a range that does not include today.  The most recent date is always 4 days in the past, even when there are transactions from the current day.  This is true no matter what chart range is selected.  The chart ranges are correct (7D shows 7 days worth of data) but the entire range is always shifted 4 days.

**To Reproduce**
It's true for every single one of the charts. There are no specific steps for me.  Create any account...add any transactions...the chart ends on the wrong day.  Sync the account just to be safe...the chart still ends on the wrong day.

**Expected behavior**
The chart range should go all the way to the current day.

**What version of Maybe are you using?**
Self hosting v0.2 alpha.  Docker installation.
```yaml
services:

  app:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - ./storage:/rails/storage
    network_mode: host
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      SELF_HOSTING_ENABLED: true
      DB_HOST: localhost
      RAILS_FORCE_SSL: false
      RAILS_ASSUME_SSL: false
      POSTGRES_USER: postgres
      GOOD_JOB_EXECUTION_MODE: async
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
```

**What operating system and browser are you using?**
It's true on Chromium based browsers and Firefox on both windows machines and linux.

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/1fd14fe0-4d86-4dd6-8d10-f5a3680c14a9)

**Additional context**
Been self-hosting since docker images have been available.  Update nearly every release by downloading the new image and spinning up the container again.  I believe this error has been true from the very beginning, but I don't exactly recall.

New transactions auto-populate with the correct date and logs show the correct UTC so the system has the correct date-time information.
