### ISSUE TITLE
Bug: Transactions from CSV import successfully, but they don't actually show up anywhere

### ISSUE THREAD

**Issue by buresdv** [maybe-finance/maybe#1662]
**Describe the bug**
I'm trying to import new transactions from a CSV file. The import finishes successfully, but the transactions never show up anywhere in the app.

**To Reproduce**
1. Go to `Settings → Imports`
2. Click `New Import` to start the import wizard, and select `Import transactions`
3. Import the CSV as usual. I'm using the `;` separator
4. Transactions get imported successfully, but they don't show up

**Expected behavior**
Transactions get imported and show up in graphs, overviews, etc.

**What version of Maybe are you using?**
`Self-hosted`, version `0.3.0`

**What operating system and browser are you using?**
Server:
- Fedora Server 41
- Docker Compose

Client:
- MacBook Air M3
- Safari 18.2

**Screenshots / Recordings**
[List of imports, which were completed successfully](https://github.com/user-attachments/assets/9683d1bf-ae70-4596-9eb7-a1663ef55e79)

[The transactions are not in the overview](https://github.com/user-attachments/assets/fe6d5436-fce4-441a-8407-1d4862d23f19) (September 27th is the date of the last transaction from the last quarter. I'm trying to import data from September until the end of December)

**Additional context**
Imports worked last time I tried them during the last quarter, around September 30th. 

Here are the logs:
[App](https://pastebin.com/BFkjm7hr)
[Database](https://pastebin.com/N0r05AVY)

And here's my Compose file:
```yaml
services:

  app:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - (app):/rails/storage
    ports:
      - 8292:3000
    restart: unless-stopped
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - (database):/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app-storage:
  postgres-data:
```
