### ISSUE TITLE
Bug: Incorrect Adding Expense Behavior and Accounts not Updating

### ISSUE THREAD

**Issue by JonA02** [maybe-finance/maybe#1838]
**Where did this bug occur? (required)**

- [x] I am a self-hosted user reporting a bug from my self hosted app

**Describe the bug**
When adding an expense, it for some reason does not "act" like an expense. It instead adds to current balance of the account (check video). Another issue is that the Account's Balance does not update as well (this may be as a result of it adding to the current balance). 

Also (although not shown here, maybe these bugs are connected, if required I'll make another issue), when creating an "Other Liability" account and transferring from the Checking account to the Liability Account, the balance again does not update. 

Just for further clarification, I created the test account and put the initial value at $100. Then added an expense transaction of $10 to the account. 

**To Reproduce**
1. Create a Depository Account
2. Select "Enter Account Balance" under "How would you like to add it?"
3. Enter in Depository Account Details (Account Name, Current Balance [$100 in my testing case], and Select Checking under subtype)
4. Select "Transactions" in sidebar
5. Select "New Transaction" on the top right
6. Ensure Expense is selected
7. Enter Transaction Information ($10 Expense in my case)
8. Select "Add Transaction"
9. Select Depository Account in sidebar (Test Checking Account in my case)
10. See Errors

**Expected behavior**
The Expense is treated as an expense and hence the balance is shown correctly.

**Screenshots / Recordings**
https://drive.google.com/file/d/1JBoNQBaQi6W6RV0z5uqM5bPRyhTpccYu/view?usp=sharing

**Environment**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

**Docker Compose File**
```
# ===========================================================================
# Example Docker Compose file
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example Docker Compose configuration for self hosting
# Maybe on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup, but may require modification
# for your specific environment.
#
# Setup:
# ------
#
# To run this, you should read the setup guide:
#
# https://github.com/maybe-finance/maybe/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# ----------------
#
# If you run into problems, you should open a Discussion here:
#
# https://github.com/maybe-finance/maybe/discussions/categories/general
#

services:

  app:
    image: ghcr.io/maybe-finance/maybe:latest

    volumes:
      - app-storage:/rails/storage

    ports:
      - 3000:3000

    restart: unless-stopped

    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app-storage:
  postgres-data:
```
