### ISSUE TITLE
Bug: Cannot to postgresql - Docker on mac os

### ISSUE THREAD

**Issue by giraudvalentin** [maybe-finance/maybe#1887]
Hi, good project, maybe (😆 ) not perfect. but want want to made my opinion and maybe help this project,
but i'm blocked

**Where did this bug occur? (required)**

- [x] I am a self-hosted user reporting a bug from my self hosted app (DOCKER)
- [ ] I am a user of Maybe's paid app : no

**Describe the bug**

**To Reproduce**
1. Lauch docker-compose based on sample,
2. Cant connect to pgsql db from local OS MAC OS host
3. Docker show containers is started
```
❯ docker ps -a | grep maybe
166fc948ffdf   ghcr.io/maybe-finance/maybe:latest           "/rails/bin/docker-e…"   9 minutes ago   Up 9 minutes                0.0.0.0:8283->3000/tcp             maybe-finance_bifamily
db1c6e378352   postgres:16                                  "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes (healthy)      5432/tcp, 0.0.0.0:7273->3000/tcp   maybe_finance_bifamily-postgres-1``
```
4. show docker compose setup 
```

services:

  app:
    container_name: maybe-finance_bifamily
    image: ghcr.io/maybe-finance/maybe:latest

    volumes:
      - ./app-storage:/rails/storage

    ports:
      - 8283:3000

    restart: unless-stopped

    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7273:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Expected behavior**
I know i'm having a problem with docker container networking but cant figure why i'm able to connect to db.
I want to connect to my db to docker container
- this command not work : `mysql -umaybe_user -pPASSWORD -hlocalhost --port=7273` : this command return ` Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)` 
- I'm already working well with mysql driver on a db postregsql database for my work but i can't figure why i cant with this project. docker is too complitacted for networking i think.
- Same from my IDE :

<img width="947" alt="Image" src="https://github.com/user-attachments/assets/1c28fc64-73b4-447a-aa00-1e76b3b1a090" />

- 

1. I expect to be able to connect to docker

Anyone as an idea ? Maybe we can add solution to the troubleshing section
