### ISSUE TITLE
Unable to start the container

### ISSUE THREAD

**Issue by tismofied** [maybe-finance/maybe#2030]
I borrowed someone's compose and it seems to be working now but I am still having issues sometime where I get something is wrong page.

```

services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - app-storage:/rails/storage
    ports:
      - 3900:3000
    restart: unless-stopped
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  app-storage: null
  postgres-data: null
networks: {}
```

I just tried to add a picture that 15kb but I get this error

![Image](https://github.com/user-attachments/assets/6272fe71-c3c8-4d61-a623-abccc4d81f5d)

also have this in the logs:

```

E, [2025-03-28T14:54:48.850997 #1] ERROR -- : [ActiveJob] Failed enqueuing ActiveStorage::AnalyzeJob to Sidekiq(default): RedisClient::CannotConnectError (Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379))
F, [2025-03-28T14:54:48.852032 #1] FATAL -- : RedisClient::CannotConnectError (Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379))
```
