### ISSUE TITLE
Bug: Self-hosted setup: incorrect redirect when behind reverse proxy

### ISSUE THREAD

**Issue by sylvaindeloux** [maybe-finance/maybe#2097]
### General checklist

- [X] I have removed personal / sensitive data from screenshots and logs
- [X] I have searched [existing issues](https://github.com/maybe-finance/maybe/issues?q=is:issue) and [discussions](https://github.com/maybe-finance/maybe/discussions) to ensure this is not a duplicate issue
    
### How are you using Maybe?

- [ ] I am a paying Maybe customer (hosted version)
  - Paying Maybe users can also open requests in Intercom (if there is sensitive info involved)
- [X] I am a self-hosted user

### Self hoster checklist

_Paying, hosted users should delete this entire section._

If you are a self-hosted user, please complete all of the information below.  Issues with incomplete information will be marked as `Needs Info` to help our small team prioritize bug fixes.

- Self hosted app commit SHA (find in user menu): latest
  - [X] I have confirmed that my app's commit is the latest version of Maybe
- Where are you hosting?
  - [ ] Render
  - [X] Docker Compose
  - [ ] Umbrel
  - [ ] Other (please specify)

---

## Bug description

Unable to use behind a reverse proxy (Traefik).

### To Reproduce

Install Docker and run my Docker Compose stack.

Request on Maybe will return a "Gateway Timeout" issue.

Use "docker logs -f maybe" command to see the log:

```
I, [2025-04-13T08:56:31.306777 #1]  INFO -- : Processing by PagesController#dashboard as */*
I, [2025-04-13T08:56:31.309937 #1]  INFO -- : {message: "Completed 302 Found in 4.70064ms", event: {http_response_sent: {body: nil, content_length: nil, headers_json: "{\"x-frame-options\":\"SAMEORIGIN\",\"x-xss-protection\":\"0\",\"x-content-type-options\":\"nosniff\",\"x-permitted-cross-domain-policies\":\"none\",\"referrer-policy\":\"strict-origin-when-cross-origin\",\"location\":\"https://localhost:3000/sessions/new\",\"content-type\":\"text/html; charset=utf-8\"}", request_id: "a21f499d-e70f-4dd6-bad3-e5b252489cca", service_name: nil, status: 302, duration_ms: 4.70064}}}
```

We have a redirection to localhost:3000 here, I think the issue is here, with my Traefik configuration.

This might be related to trusted proxy settings: I suspect Rails is not trusting the reverse proxy headers (X-Forwarded-*), and defaults to thinking it’s running locally on localhost:3000.
Let me know if this should be fixed in the app config, or if I missed an env var.

### Expected behavior

The website works with Traefik.

### Screenshots and/or recordings

Here is my Docker Compose file:

```
services:
    traefik:
        image: traefik:v3.3
        restart: always
        command:
            - --api=true
            - --api.dashboard=true
            - --api.insecure=false
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
            - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - web
    maybe:
        image: ghcr.io/maybe-finance/maybe:latest
        restart: always
        depends_on:
            maybe-db: { condition: service_healthy }
            maybe-redis: { condition: service_healthy }
        environment:
            SECRET_KEY_BASE: ${MAYBE_SECRET_KEY}
            SELF_HOSTED: "true"
            HOST: ${MAYBE_HOST}
            RAILS_HOST: ${MAYBE_HOST}
            RAILS_DEFAULT_URL: https://${MAYBE_HOST}
            RAILS_RELATIVE_URL_ROOT: /
            RAILS_FORCE_SSL: "true"
            RAILS_ASSUME_SSL: "true"
            DB_HOST: maybe-db
            DB_PORT: 5432
            REDIS_URL: redis://maybe-redis:6379/1
            POSTGRES_USER: ${MAYBE_DB_USER}
            POSTGRES_PASSWORD: ${MAYBE_DB_PASSWORD}
            POSTGRES_DB: ${MAYBE_DB_NAME}
            OPENAI_ACCESS_TOKEN: ${MAYBE_OPENAI_ACCESS_TOKEN}
        volumes:
            - ./maybe/storage:/rails/storage
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.maybe.rule=Host(`${MAYBE_HOST}`)"
            - "traefik.http.routers.maybe.entrypoints=websecure"
            - "traefik.http.routers.maybe.tls.certresolver=letsencrypt"
            - "traefik.http.services.maybe.loadbalancer.server.port=3000"
        networks:
            - web
            - maybe
networks:
    web:
        external: true
    maybe:
        driver: bridge
```
