### ISSUE TITLE
Bug: Unable to use hostname as DB_HOST

### ISSUE THREAD

**Issue by Tymec** [maybe-finance/maybe#730]
**Describe the bug**
I am unable to use a hostname for the `DB_HOST` env variable, while using `localhost` or any valid IP address works. When the container starts, it successfully creates the `maybe_production` database in postgres, but crashes after the "Booting Puma" line.

**To Reproduce**
Followed the docker compose setup and set `DB_HOST=db`. Additionally I set the postgres container hostname to `db`.

docker-compose.yaml:
```yaml
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.monitor-only: true
    ports:
      - "3883:3000"
    networks:
      - main
    env_file:
      - path: .env
    environment:
      RAILS_ENV: production
      RAILS_FORCE_SSL: false
      RAILS_ASSUME_SSL: false
    depends_on:
      db:
        condition: service_healthy

  db:
    hostname: maybe_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - main
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  main:
    external: true

volumes:
  db-data:
```

**Expected behavior**
The hostname should be properly resolved.

**Screenshots / Recordings**
maybe logs:
![image](https://github.com/maybe-finance/maybe/assets/2727109/42be00f1-134f-4fc7-8fb3-d70886d398dc)
postgres logs:
![image](https://github.com/maybe-finance/maybe/assets/2727109/71e1581b-3473-422c-81ee-46b11d8e7a20)
