### ISSUE TITLE
Bug: Value does not update when manually add newest price in history

### ISSUE THREAD

**Issue by hxwang-463** [maybe-finance/maybe#804]
**Where did this bug occur?**

- [ ] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**
When I add the newest value in history, the price does not update.

**Expected behavior**
the value gets updated, and shown changes in the price chart

**Screenshots / Recordings**
![image](https://github.com/maybe-finance/maybe/assets/34204376/cd735d1c-4639-41f2-9749-83973f8e578a)

**Comment by zachgoll** [comment]
@hxwang-463 does this bug still occur for you?  I think it may have been fixed in some of our recent updates.

**Comment by hxwang-463** [comment]
I am using Version: v0.1.0-alpha.3 and the bug still here; Actually, I am kind of confused about the relationship between History and Transactions, can you please illustrate? like how should I add amount when I have new paycheck? how should I update value when the price in market goes up?

**Comment by zachgoll** [comment]
@hxwang-463 could you hit the "re-sync" icon at the top of the account page or try updating the valuation one more time to trigger an account sync?  I think the balance should update after you do that.  Let me know if it doesn't (screencast is ideal).

To answer your questions:

- To add a paycheck, you should add a new "Transaction"
- To update a market value, we don't quite have that functionality available yet, so the best option would be to add a new "History" item to update the value of the account

**Comment by hxwang-463** [comment]
https://github.com/maybe-finance/maybe/assets/34204376/a78ba01e-8ea8-462f-814f-4871ed0fd097

let me know if I did something wrong

**Comment by zachgoll** [comment]
@hxwang-463 after you update the history, you should not have to click the sync button.  Other than that, it appears that you're doing things correctly.

I ran this on my own self hosted instance and was not able to reproduce this.  Could you:

- Share your docker compose config (remove all the secret environment variable values, just need the template you're using)
- Try adding a brand new account and seeing if it syncs?

**Comment by hxwang-463** [comment]
```
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    container_name: maybe
    restart: unless-stopped
    environment:
      SELF_HOSTING_ENABLED: true
      SECRET_KEY_BASE: ***
      DB_HOST: 172.20.0.25
      DB_PORT: 5432
      POSTGRES_PASSWORD: ***
      POSTGRES_USER: ***
      RAILS_FORCE_SSL: false
      RAILS_ASSUME_SSL: false
      REQUIRE_INVITE_CODE: true
      TZ: America/New_York

    networks:
      my_network:
        ipv4_address: 172.20.0.20

networks:
  my_network:
    external: true
```
and the database is `postgres:latest`
If the docker compose seems right to you, then I will try to re-deploy. Thanks!
